CREATE TABLE IF NOT EXISTS counter(
  id INTEGER PRIMARY KEY,
  visits INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO counter(id, visits) VALUES(1, 0);

CREATE TABLE IF NOT EXISTS guestbook (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
